"""
e08_ocd/fields/_keywords.py
===============================
Listes de référence pour la classification locale (particulier / ETS / entreprise)
partagée par NomDonneurOrdre et Bénéficiaire — portées telles quelles depuis
DataCleaning-PipelineField-BCMDG/nomdonneurordre/keywords.py.

Préfixé `_` (module privé au package e08_ocd/fields/) : pas un référentiel piloté
par YAML comme devise_referentiel.json — des constantes Python utilisées par
e08_ocd/fields/_entity_matching.py.
"""
from __future__ import annotations

# Suffixes/mots-clés juridiques ou organisationnels indiquant clairement une ENTREPRISE
# (utilisés pour disqualifier la classification "particulier").
KEYWORDS_ENTREPRISE = {
    "SARL", "SA", "SAS", "SNC", "GIE", "EURL", "SUARL", "SARLU",
    "LTD", "LLC", "INC", "CORP", "GMBH", "CO",
    "ETS", "ETB", "ETABLISSEMENT", "ETABLISSEMENTS",
    "SOCIETE", "STE", "COMPAGNIE", "CIE", "COOPERATIVE",
    "GROUPE", "GROUP", "GROUPEMENT", "HOLDING", "ENTREPRISE",
    "AGENCE", "CABINET", "BUREAU",
}

# Prénoms / particules de noms — couverture exhaustive (arabes/mauritaniens,
# ouest-africains, européens) + particules (OULD, MINT, BINT...).
PRENOMS_KEYWORDS = {
    # Masculins arabes / mauritaniens
    "AHMAD", "AHMED", "AHMEDOU", "AHMEDOUH", "AHMEDDOU", "YAHYE", "SIDAHMED", "IDOUMOU",
    "MOHAMMED", "MOHAMED", "MOHAMEDOU", "MOUHAMED", "MUHAMMAD", "MED",
    "ABDALLAH", "ABDALLAHI", "ABDELLAHI", "ABDOUL", "ABDOU", "ABDEL", "MOHAMEDHEN", "SOUVI",
    "ABDERRAHMANE", "ABDERAHMANE", "ABDARRAHMAN", "ABDELRAHMAN",
    "ABDALLA", "ABDELKADER", "ABDELKARIM", "ABDELLAH", "ABDELHAY",
    "ABDELAZIZ", "ABDELLATIF", "ABDOULAYE",
    "SIDI", "SIDINA", "SIDATY", "SIDIYA", "SAYID", "SAID", "SAIDOU",
    "BRAHIM", "IBRAHIM", "IBRAHIMA", "BRAHEEM",
    "CHEIKH", "SHEIKH", "CHEIKHNA", "CHEIKHANI", "CHEIKHENA",
    "OMAR", "OUMAR", "ALI", "ALY", "ELY",
    "HASSAN", "HASSANE", "HUSSEIN", "HOUSSEIN", "HUSSEINI",
    "YAHYA", "YAHIA", "YAHYAOUI",
    "ISSELMOU", "ISMAIL", "ISMAILE", "ISMAEL",
    "IDRISS", "IDRISSA", "DRISS",
    "MOKHTAR", "MOCTAR", "MAKHTAR",
    "MOUSSA", "ISSA", "YOUSSEF", "YOUCEF", "YOUSSOUF", "YUSUF",
    "OUSMANE", "OSMAN", "OTHMAN", "OUSEINI",
    "LEMINE", "LIMAM", "LIMAMA", "ELIMAM",
    "TALEB", "ETTALEB", "LELLAH", "LEHBIB",
    "SALEM", "SALIHY", "SALIH", "SALEH", "SALECK", "SELECK",
    "HORMA", "HAMOUD", "HAMODY", "HAMOUDI", "HAMODI",
    "MAHFOUDH", "MAHFOUD", "MAHMOUD", "MAHMUD", "MAHMOUDI", "MAHFOUZ",
    "MALAININE", "MALAINI", "MELAININE", "MEME", "EMEME",
    "BABA", "BABAH", "BABACAR",
    "DAH", "DADDAH", "DEH", "DADAH",
    "MUSTAFA", "MOUSTAPHA", "MUSTAPHA",
    "RABANI", "RABBANI", "RABAI", "RABIE", "RABIA",
    "HAMED", "HAMAD", "HAMID", "HAMIDOU", "HAMETT", "HAMETI",
    "TAHA", "TAHIR", "TAHER",
    "BOUH", "BOUHA", "BOUHAOU", "BOUHAYA",
    "KHATRI", "KHATRY", "KHALIVA", "KHALIFA",
    "YESLIM", "YESLEM", "YESAA",
    "BENNANE", "BENBAH",
    "JEMAL", "JEDDOU", "JIDDOU", "JEMIL", "JEMILE",
    "VAH", "VEH", "VATAH", "VELY", "VELAH",
    "ZIDANE", "ZEINE", "ZEIN", "ZEINI",
    "KARIM", "KARIME", "KAMEL", "KAMAL",
    "AMINE", "AMIN", "ANOUAR", "ANWAR",
    "BACHIR", "BACHEER", "BECHIR",
    "DJIBRIL", "GIBRIL", "DJIBY",
    "MAOULOUM", "MAOULOOM",
    "BEYADE", "BEYADI",
    "GHASSEM", "GHANEM", "GHALI",
    "GHOUEIZI", "GHAZALI",
    "WELY", "WALI", "WELID", "WALID",
    "EBNOU", "EBNI", "EBDEMEL",
    "TOLBA", "TOULBA",
    "MELLAH", "MAALI", "MAALY",
    "MAKE", "MAKKI", "MODY", "MOULDI",
    "MOULAY", "MOULAYE",
    "HAFED", "HAFEDH", "HAFEZ", "ELHAFED",
    "NOUH", "NOUHA",
    "EWFA", "ASKER",
    "MALICK", "LEMRABOTT", "LEMRABOT", "LEMRABOTH",
    "YEHDHIH", "MEHDI", "MAHDI",
    "DEDDAH",
    "ZOUBEIR", "ZOUBAIR",
    "MAALOUM", "ZAKARIA", "ZAKARYA",
    "TIJANI", "TIJANY", "TIDIANE", "TIDJANI",
    "MOULAYINI",
    "WEDDOU", "KEDAH", "KEDDAH",
    "RYAN", "ADAM", "ADEM",
    "SOUMARE", "CAMARA",
    "BABY", "BAYE", "BAYI",
    "SIDDIK", "SIDIK",
    # Patronymes mauritaniens fréquents dans "ETS XYZ" personnel
    "BOUKHARY", "BOUAMATOU", "HMAYENE", "TEREKZI", "TEREKZY", "TEYSSIR",
    "BIRIGNI", "TANDIA", "KASSE", "TEYBA", "MOWLOUD",
    "BERIHIL", "BERROU", "BERROUI", "BOUMAATI", "DAYNANE",
    "HMAD", "NAJI", "LARBI", "LAGHDAFI", "LAGHDAF",
    # Masculins arabes / mauritaniens additionnels
    "ETHMANE", "ETHMAN", "OTMANE", "OUSMAN",
    "ZEIDANE", "ZEIDAN",
    "TARIK", "TAREQ", "TAREK", "TARIQ",
    "VATIH", "VATH", "VALL", "VEILLY",
    "WAHED", "WAGHEF",
    "HACEN", "HOCEINE", "HOCEYNE",
    "LAKHEL", "LAKHAL", "AHEL",
    "MOULOUD",
    "AHID", "EID",
    "MENTAH",
    "BIROU", "BIHO", "BIH",
    "BACHIROU",
    "NIBRAS", "NIBRASS",
    "RIDA", "RIDOU", "RIDOUANE",
    "DIDI",
    "SAMI", "SAMY",
    "ZARROUGUI", "ZARROUK",
    "KHARC",
    "DEYE",
    "AHMEDNAH",
    "MAALOUMA",
    "HENDI",
    "BOULAHOUEL",
    # Féminins arabes / mauritaniens additionnels
    "LEYLA", "LEILA", "LAILA",
    "NOURA", "NORA", "NORHANE",
    "HABIBA", "ZOHRA", "ZAHRA",
    "SVA", "SVEIRA",
    "KHEIRA", "KHEIRY", "OUMOULKHEIRY",
    "ZOUBIDA", "NAJOUA",
    "KHARDIATA", "MEISSA", "MEKSA",
    "MAKHA", "MENNANA", "MELIKA",
    "YENA", "TIMA", "TOUBA", "VAYA",
    "VEYDA", "VEYNA",
    "NEJWA", "NEJOUA",
    "HAYA", "HUDA", "HODA",
    "SOUMEYA", "SAMIA",
    "AHLAM", "AMAL", "AMEL",
    # Ouest-africains additionnels (Sénégal, Mali, Guinée)
    "SOULEYMANE", "SOULEY", "SOULAYMANE",
    "COULIBALY", "TRAORE", "KEITA", "KONATE", "DRAME",
    "CISSE", "SISSE", "TOURE", "TURE",
    "KOITA", "DIOP", "DIAGNE", "DIALLO",
    "ALPHA", "ALFA",
    "LAMIN", "LAMINE",
    "ABLAYE", "ABLAY",
    "BOCAR", "BOKAR",
    "SAGNA", "SANGARE",
    "MBAYE",
    "WADE", "LADJI",
    "LO", "KANE", "DIAKHO",
    "THIERNO", "TIERNO",
    "BIRANE", "BIRA",
    "SAMORY", "FODE",
    "OUSEYNOU", "MOMODOU",
    # Variations supplémentaires
    "SIDIA", "AHMEDOUM",
    "ELHADJI", "HADJI", "ELHADJ",
    # Prénoms féminins arabes / mauritaniens
    "MARIEM", "MARYEM", "MARIA", "MARIAM", "MARYAM", "MARIAMA",
    "FATIMA", "FATIMETOU", "FATMA", "FATIMATOU", "FATY",
    "LALLA", "LALA", "LELLA",
    "AICHA", "AISHA", "AICHATOU", "AICHE", "AICHETOU",
    "AMINATA", "AMINETOU", "AMINA", "AMNA",
    "ZEINAB", "ZEINEB", "ZEIDA", "ZEINOUNA", "ZAYNAB", "ZAINAB", "ZEINEBOU",
    "KHADIJA", "KHADIJETOU", "KHADIJTOU", "KHADY",
    "MEYMOUNA", "MEYMOUN", "MEIMOUNA", "MAIMOUNA",
    "NOUHAYLA",
    "SOUKEINA", "SOUKAINA", "SOUKEINETOU",
    "VATIMETOU", "VATMA",
    "MOUNINA", "MOUNIA", "MOUNIRA", "MUNIRA",
    "NEINE", "NEINI",
    "OUKADDOUR",
    "MARIETOU",
    "OUMOU", "UMMU", "UMM",
    "RAMA", "RAMATA", "RAMATOULAYE",
    "ADJA", "HADJA", "HADIA",
    "BINTA", "BINTOU", "BENTE",
    "DJENABA", "DIENABA",
    "ROUGUI", "ROUGUIATOU",
    "AISSATA", "AISSATOU", "AISSE",
    "RAKIA", "RAKIYA", "RAQUIA",
    "SAFI", "SAFIA", "SAFIATOU", "SAFY",
    "SALIMATA",
    "BABIYE", "LEJHOURY", "MAADH", "SAVIYE", "CHACH",
    "HAYAT",
    "MELHA", "MELLA",
    "AZIZA", "AZZIZA",
    "JEMILA", "JAMILA", "DJAMILA",
    "FATOU", "FATOUMATA",
    "AWA", "AWWA",
    "KADY",
    "FANTA",
    "DIARRA",
    "TOUTY", "TUTU",
    "NAJYA", "NAJIA", "NAJET", "NAJAT",
    "MAYSSA", "MEYSSA",
    "FATIMATA",
    # Prénoms ouest-africains (Sénégal, Mali...)
    "ALIOU", "ALIOUNE", "MAMADOU", "AMADOU",
    "BOUBACAR", "BOUBOU",
    "SEYDOU", "SEYNI", "SEYDINA",
    "SALIF", "SALIOU",
    "BAKARY", "BAKARI",
    "MODIBO",
    "DEMBA", "DEMBELE",
    "PAPA", "PAPE",
    "BIRAME", "BIRAM",
    "SAMBA", "SAMBOU",
    "DOUDOU",
    "NIANG", "NDIAYE", "DIENG", "DIAW", "DIA", "DIATTA",
    "BARRY", "BAH", "BARI",
    "SECK", "SOW", "SY",
    "FALL", "GUEYE", "BA",
    # Prénoms européens pouvant apparaître
    "JEAN", "PIERRE", "MARIE", "ANNE",
    "PAUL", "PHILIPPE", "MICHEL", "MICHELLE",
    "JACQUES", "FRANCOIS", "FRANCOISE",
    "LOUIS", "HENRI",
    "OLIVIER", "DAVID",
    "DENIS", "CHARLES",
    "CHRISTIAN", "CHRISTINE", "CATHERINE",
    "BERNARD", "ALAIN",
}

# Outliers évidents (valeurs de bruit connues, indépendamment du référentiel).
OUTLIERS_EVIDENTS = {
    "STRING", "TEST", "TEST CLIENT", "TESTS",
    "NULL", "NONE", "NAN", "NA", "N/A", "N A",
    "INCONNU", "VIDE", "AUCUN", "NEANT", "SANS OBJET",
    "NON RENSEIGNE", "FAUX PARTICULIERS", "A NE PAS UTILISER",
    "NOMDONNEURORDRE", "NOM DONNEUR ORDRE",
    "-", "--", "_", "0", "1",
}
